apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  serviceAccountName: roboshop-catalogue-sa
  containers:
    - name: debug
      image: amazonlinux:2
      command: ["/bin/bash", "-c", "sleep 3600"]
  restartPolicy: Never


