apiVersion : v1
kind : Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  serviceAccountName: roboshop-frontend-sa
  containers:
    - name: frontend
      image: tejaswinidockerhub/frontend
      imagePullPolicy: Always
---
apiVersion : v1
kind : Pod
metadata:
  name: catalogue
  labels:
    app: catalogue
spec:
  serviceAccountName: roboshop-catalogue-sa
  initContainers:
    - name: parameters-pull
      image: docker.io/tejaswinidockerhub/init-container-parameters-image
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /parameters
          name: parameters
      env:
        - name: PARAMS
          value: "dev.roboshop.catalogue.MONGO_URL,MONGO_URL"
  containers:
    - name: catalogue
      image: tejaswinidockerhub/catalogue
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /parameters
          name: parameters
  volumes:
    - name: parameters
      emptyDir: { }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: catalogue-schema-load
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: roboshop-catalogue-sa
      restartPolicy: Never
      volumes:
        - name: parameters
          emptyDir: { }
      initContainers:
        - name: parameters-pull
          image: docker.io/tejaswinidockerhub/init-container-parameters-image
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /parameters
              name: parameters
          env:
            - name: PARAMS
              value: "dev.roboshop.docdb.username,DOCDB_USER dev.roboshop.docdb.pass,DOCDB_PASS,dev.roboshop.docdb.endpoint,DOCDB_ENDPOINT"
      containers:
        - name: schema-load
          image: docker.io/tejaswinidockerhub/schema-loader
          imagePullPolicy: Always
          env:
            - name: COMPONENT
              value: catalogue
            - name: SCHEMA_TYPE
              value: mongo
          volumeMounts:
            - mountPath: /parameters
              name: parameters
---
apiVersion : v1
kind : Pod
metadata:
  name: user
  labels:
    app: user
spec:
  serviceAccountName: roboshop-user-sa
  initContainers:
    - name: parameters-pull
      image: docker.io/tejaswinidockerhub/init-container-parameters-image
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /parameters
          name: parameters
      env:
        - name: PARAMS
          value: "dev.roboshop.user.MONGO_URL,MONGO_URL dev.roboshop.user.REDIS_HOST,REDIS_HOST"
  containers:
    - name: user
      image: tejaswinidockerhub/user
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /parameters
          name: parameters
  volumes:
    - name: parameters
      emptyDir: { }
---
apiVersion : v1
kind : Pod
metadata:
  name: cart
  labels:
    app: cart
spec:
  serviceAccountName: roboshop-cart-sa
  initContainers:
    - name: parameters-pull
      image: docker.io/tejaswinidockerhub/init-container-parameters-image
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /parameters
          name: parameters
      env:
        - name: PARAMS
          value: "dev.roboshop.cart.REDIS_HOST,REDIS_HOST dev.roboshop.cart.CATALOGUE_HOST,CATALOGUE_HOST,dev.roboshop.cart.CATALOGUE_PORT,CATALOGUE_PORT"
  containers:
    - name: cart
      image: tejaswinidockerhub/cart
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /parameters
          name: parameters
  volumes:
    - name: parameters
      emptyDir: { }
---
apiVersion : v1
kind : Pod
metadata:
  name: payment
  labels:
    app: payment
spec:
  serviceAccountName: roboshop-payment-sa
  initContainers:
    - name: parameters-pull
      image: docker.io/tejaswinidockerhub/init-container-parameters-image
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /parameters
          name: parameters
      env:
        - name: PARAMS
          value: "dev.roboshop.payment.CART_HOST,CART_HOST dev.roboshop.payment.CART_PORT,CART_PORT dev.roboshop.payment.USER_HOST,USER_HOST dev.roboshop.payment.USER_PORT,USER_PORT dev.roboshop.payment.AMQP_HOST,AMQP_HOST dev.roboshop.payment.AMQP_USER,AMQP_USER dev.roboshop.payment.AMQP_PASS,AMQP_PASS"
  containers:
    - name: payment
      image: tejaswinidockerhub/payment
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /parameters
          name: parameters
  volumes:
    - name: parameters
      emptyDir: { }
---
apiVersion : v1
kind : Pod
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  serviceAccountName: roboshop-shipping-sa
  initContainers:
    - name: parameters-pull
      image: docker.io/tejaswinidockerhub/init-container-parameters-image
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /parameters
          name: parameters
      env:
        - name: PARAMS
          value: "dev.roboshop.shipping.CART_ENDPOINT,CART_ENDPOINT dev.roboshop.shipping.DB_HOST,DB_HOST"
  containers:
    - name: shipping
      image: tejaswinidockerhub/shipping
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /parameters
          name: parameters
  volumes:
    - name: parameters
      emptyDir: { }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: shipping-schema-load
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: roboshop-shipping-sa
      restartPolicy: Never
      volumes:
        - name: parameters
          emptyDir: { }
      initContainers:
        - name: parameters-pull
          image: docker.io/tejaswinidockerhub/init-container-parameters-image
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /parameters
              name: parameters
          env:
            - name: PARAMS
              value: "dev.roboshop.rds.endpoint,DOCDB_HOST dev.roboshop.rds.username,DB_USER,dev.roboshop.rds.password,DOCDB_PASS"
      containers:
        - name: schema-load
          image: docker.io/tejaswinidockerhub/schema-loader
          imagePullPolicy: Always
          env:
            - name: COMPONENT
              value: shipping
            - name: SCHEMA_TYPE
              value: mysql
          volumeMounts:
            - mountPath: /parameters
              name: parameters
---
apiVersion : v1
kind : Pod
metadata:
  name: dispatch
  labels:
    app: dispatch
spec:
  containers:
    - name: dispatch
      image: tejaswinidockerhub/dispatch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: roboshop-frontend-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::522814736516:role/dev-roboshop-eks-pod-role-for-frontend-ssm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: roboshop-catalogue-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::522814736516:role/dev-roboshop-eks-pod-role-for-catalogue-ssm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: roboshop-user-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::522814736516:role/dev-roboshop-eks-pod-role-for-user-ssm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: roboshop-cart-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::522814736516:role/dev-roboshop-eks-pod-role-for-cart-ssm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: roboshop-payment-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::522814736516:role/dev-roboshop-eks-pod-role-for-payment-ssm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: roboshop-shipping-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::522814736516:role/dev-roboshop-eks-pod-role-for-shipping-ssm

